### ISSUE TITLE
Possible to start the shell directly as admin through flags?

### ISSUE THREAD

**Issue by Trung0246** [nyaosorg/nyagos#437]
I'm not sure if there's something like `nyagos.exe --admin` or something like that beside `su`.

Also is it possible to disable `su` behavior of launching an entire new windows if configuring nyagos running through terminal emulator (like wezterm and cmder) if the flag path is not possible?

**Comment by hymkor** [comment]
nyagos.exe can restart itself as administrator, but it runs on a new window.

For example

- `nyagos.exe --norc -e "nyagos.shellexecute('runas',nyagos.exe)"` 
- `nyagos.exe --norc -e "nyagos.shellexecute('runas','wezterm','start ' .. nyagos.exe )"`

I do not know how to prevent from opening a new window because it is the specification of the Windows-API `shellexecute` and terminals .

**Comment by hymkor** [comment]
Alternatively, you can start the terminal program as administrator.

```
sugui wezterm.exe "start (DIR)\nyagos.exe"
```

[sugui](https://github.com/hymkor/sugui-rs) is my tool that starts programs with administrator privileges on Microsoft Windows.

**Comment by hymkor** [comment]
I close this issue , but please reopen if you have any additional questions or requests.
